spring:
  datasource:
    url: jdbc:mysql://192.168.12.156:3308/agile_service?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: handhand
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  cloud:
    stream:
        kafka:
          binder:
            brokers: 127.0.0.1:9092
            zkNodes: 127.0.0.1:2181
        default-binder: kafka
    config:
      failFast: true
      retry:
        maxAttempts: 6
        multiplier: 1.5
        maxInterval: 2000
      uri: localhost:8010
      enabled: false
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
  cache:
    type: redis
choerodon:
  event:
    consumer:
      enabled: true # 是否开启，不设置默认开启
      queue-type: kafka # 消息队列类型
      enable-duplicate-remove: true # 是否开启去重
      failed-strategy: nothing # 失败策略。支持nothing(什么都不做), send_back_event_store(回传到event store)两种
      retry:
        enabled: true # 是否开启重试功能
      kafka:
        bootstrap-servers: localhost:9092 # kafka地址
  saga:
    consumer:
      enabled: true # 是否启用消费端
      thread-num: 5  # 消费线程数
      max-poll-size: 200 # 每次拉取的最大消息数量
      poll-interval-ms: 1000 # 拉取消息的间隔(毫秒)，默认1000毫秒
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 1
security:
  basic:
    enabled: false
  ignored: /v2/api-docs
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
feign:
  hystrix:
    shareSecurityContext: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
services:
  attachment:
    url: example.com
